
-- ==========================================================
-- CÓRDOBA CASTING · AULA VIRTUAL
-- MIGRACIÓN: PORTADAS + PERMISOS DOCENTES + FORO
-- ==========================================================

-- 1. Portada opcional personalizada para cada curso
alter table public.courses
add column if not exists cover_image_url text;

-- 2. Permisos adicionales para profesores
-- Un profesor sólo puede modificar cursos en los que esté asignado.
drop policy if exists "Teachers can update assigned courses" on public.courses;
create policy "Teachers can update assigned courses"
on public.courses
for update
to authenticated
using (
  public.current_user_role() = 'teacher'
  and public.user_belongs_to_course(id)
)
with check (
  public.current_user_role() = 'teacher'
  and public.user_belongs_to_course(id)
);

-- Puede editar módulos de sus cursos, pero no crearlos ni eliminarlos.
drop policy if exists "Teachers can update assigned modules" on public.modules;
create policy "Teachers can update assigned modules"
on public.modules
for update
to authenticated
using (
  public.current_user_role() = 'teacher'
  and public.user_belongs_to_course(course_id)
)
with check (
  public.current_user_role() = 'teacher'
  and public.user_belongs_to_course(course_id)
);

-- Puede editar contenido de sus cursos.
drop policy if exists "Teachers can update lessons in assigned courses" on public.lessons;
create policy "Teachers can update lessons in assigned courses"
on public.lessons
for update
to authenticated
using (
  public.current_user_role() = 'teacher'
  and exists (
    select 1
    from public.modules m
    where m.id = lessons.module_id
      and public.user_belongs_to_course(m.course_id)
  )
)
with check (
  public.current_user_role() = 'teacher'
  and exists (
    select 1
    from public.modules m
    where m.id = lessons.module_id
      and public.user_belongs_to_course(m.course_id)
  )
);

-- 3. Foro
create table if not exists public.forum_threads (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  link_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_replies (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.forum_threads(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  link_url text,
  created_at timestamptz not null default now()
);

create index if not exists forum_threads_course_idx on public.forum_threads(course_id);
create index if not exists forum_replies_thread_idx on public.forum_replies(thread_id);

alter table public.forum_threads enable row level security;
alter table public.forum_replies enable row level security;

-- Ver preguntas: miembros del curso o admin.
drop policy if exists "Course members can view forum threads" on public.forum_threads;
create policy "Course members can view forum threads"
on public.forum_threads
for select
to authenticated
using (
  public.is_admin()
  or public.user_belongs_to_course(course_id)
);

-- Sólo alumnos pueden abrir una consulta, y únicamente en un curso propio.
drop policy if exists "Students can create forum threads" on public.forum_threads;
create policy "Students can create forum threads"
on public.forum_threads
for insert
to authenticated
with check (
  public.current_user_role() = 'student'
  and user_id = auth.uid()
  and public.user_belongs_to_course(course_id)
);

-- Moderación: el admin puede borrar consultas.
drop policy if exists "Admin can delete forum threads" on public.forum_threads;
create policy "Admin can delete forum threads"
on public.forum_threads
for delete
to authenticated
using (public.is_admin());

-- Ver respuestas cuando el usuario pertenece al curso de la consulta.
drop policy if exists "Course members can view forum replies" on public.forum_replies;
create policy "Course members can view forum replies"
on public.forum_replies
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.forum_threads t
    where t.id = forum_replies.thread_id
      and public.user_belongs_to_course(t.course_id)
  )
);

-- Sólo profesores asignados o admin pueden responder.
drop policy if exists "Staff can reply to forum threads" on public.forum_replies;
create policy "Staff can reply to forum threads"
on public.forum_replies
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    public.is_admin()
    or (
      public.current_user_role() = 'teacher'
      and exists (
        select 1
        from public.forum_threads t
        where t.id = forum_replies.thread_id
          and public.user_belongs_to_course(t.course_id)
      )
    )
  )
);

-- Profesores pueden editar sus propias respuestas; admin cualquiera.
drop policy if exists "Staff can update forum replies" on public.forum_replies;
create policy "Staff can update forum replies"
on public.forum_replies
for update
to authenticated
using (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and user_id = auth.uid()
  )
);

drop policy if exists "Admin can delete forum replies" on public.forum_replies;
create policy "Admin can delete forum replies"
on public.forum_replies
for delete
to authenticated
using (public.is_admin());
