-- ==========================================================
-- CÓRDOBA CASTING · AULA VIRTUAL · V9
-- ARCHIVADO + PROGRESO + CUESTIONARIOS
-- Ejecutar una sola vez antes de subir la V9.
-- ==========================================================

-- ----------------------------------------------------------
-- 1. ARCHIVADO DE CURSOS
-- ----------------------------------------------------------
alter table public.courses
add column if not exists archived_at timestamptz;

-- ----------------------------------------------------------
-- 2. PROGRESO DE CONTENIDOS
-- ----------------------------------------------------------
create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique(user_id,lesson_id)
);

alter table public.lesson_progress enable row level security;

drop policy if exists "Users can read own lesson progress" on public.lesson_progress;
create policy "Users can read own lesson progress"
on public.lesson_progress for select to authenticated
using(user_id=auth.uid());

drop policy if exists "Users can mark own lessons complete" on public.lesson_progress;
create policy "Users can mark own lessons complete"
on public.lesson_progress for insert to authenticated
with check(
  user_id=auth.uid()
  and exists(
    select 1
    from public.lessons l
    join public.modules m on m.id=l.module_id
    where l.id=lesson_progress.lesson_id
      and public.user_belongs_to_course(m.course_id)
  )
);

drop policy if exists "Users can unmark own lessons" on public.lesson_progress;
create policy "Users can unmark own lessons"
on public.lesson_progress for delete to authenticated
using(user_id=auth.uid());

-- ----------------------------------------------------------
-- 3. CUESTIONARIOS
-- ----------------------------------------------------------
create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.modules(id) on delete cascade,
  title text not null,
  description text,
  position integer not null default 1,
  is_published boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  prompt text not null,
  position integer not null default 1
);

create table if not exists public.quiz_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.quiz_questions(id) on delete cascade,
  label text not null,
  is_correct boolean not null default false,
  position integer not null default 1
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null,
  total integer not null,
  answers jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default now()
);

create index if not exists quizzes_module_idx on public.quizzes(module_id);
create index if not exists quiz_questions_quiz_idx on public.quiz_questions(quiz_id);
create index if not exists quiz_options_question_idx on public.quiz_options(question_id);
create index if not exists quiz_attempts_user_idx on public.quiz_attempts(user_id);
create index if not exists quiz_attempts_quiz_idx on public.quiz_attempts(quiz_id);

alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_options enable row level security;
alter table public.quiz_attempts enable row level security;

-- Miembro del curso puede ver la ficha del quiz publicado.
drop policy if exists "Course members can read quizzes" on public.quizzes;
create policy "Course members can read quizzes"
on public.quizzes for select to authenticated
using(
  public.is_admin()
  or exists(
    select 1 from public.modules m
    where m.id=quizzes.module_id
      and public.user_belongs_to_course(m.course_id)
      and (quizzes.is_published=true or public.current_user_role()='teacher')
  )
);

-- Admin puede eliminar quizzes. La creación/edición docente se hace mediante save_quiz().
drop policy if exists "Admin can delete quizzes" on public.quizzes;
create policy "Admin can delete quizzes"
on public.quizzes for delete to authenticated
using(public.is_admin());

-- Preguntas/opciones con respuestas correctas sólo son legibles directamente por staff.
drop policy if exists "Staff can read quiz questions" on public.quiz_questions;
create policy "Staff can read quiz questions"
on public.quiz_questions for select to authenticated
using(
  public.is_admin()
  or (
    public.current_user_role()='teacher'
    and exists(
      select 1
      from public.quizzes q
      join public.modules m on m.id=q.module_id
      where q.id=quiz_questions.quiz_id
        and public.user_belongs_to_course(m.course_id)
    )
  )
);

drop policy if exists "Staff can read quiz options" on public.quiz_options;
create policy "Staff can read quiz options"
on public.quiz_options for select to authenticated
using(
  public.is_admin()
  or (
    public.current_user_role()='teacher'
    and exists(
      select 1
      from public.quiz_questions qq
      join public.quizzes q on q.id=qq.quiz_id
      join public.modules m on m.id=q.module_id
      where qq.id=quiz_options.question_id
        and public.user_belongs_to_course(m.course_id)
    )
  )
);

-- Cada usuario ve sus propios intentos.
drop policy if exists "Users can read own quiz attempts" on public.quiz_attempts;
create policy "Users can read own quiz attempts"
on public.quiz_attempts for select to authenticated
using(user_id=auth.uid());

-- ----------------------------------------------------------
-- 4. GUARDAR / EDITAR QUIZ (STAFF)
-- ----------------------------------------------------------
create or replace function public.save_quiz(
  p_quiz_id bigint,
  p_module_id bigint,
  p_title text,
  p_description text,
  p_position integer,
  p_is_published boolean,
  p_questions jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_course_id bigint;
  v_quiz_id bigint;
  v_question_id bigint;
  q jsonb;
  opt text;
  q_index integer := 0;
  opt_index integer;
  correct_index integer;
begin
  if auth.uid() is null then raise exception 'No autenticado'; end if;

  select course_id into v_course_id from public.modules where id=p_module_id;
  if v_course_id is null then raise exception 'Módulo no encontrado'; end if;

  if not public.is_admin() and not (
    public.current_user_role()='teacher'
    and public.user_belongs_to_course(v_course_id)
  ) then
    raise exception 'Sin permiso para editar cuestionarios en este curso';
  end if;

  if trim(coalesce(p_title,''))='' then raise exception 'El cuestionario necesita un título'; end if;
  if jsonb_array_length(coalesce(p_questions,'[]'::jsonb)) < 1 then raise exception 'Agregá al menos una pregunta'; end if;

  if p_quiz_id is null then
    insert into public.quizzes(module_id,title,description,position,is_published,created_by)
    values(p_module_id,trim(p_title),coalesce(p_description,''),greatest(coalesce(p_position,1),1),coalesce(p_is_published,true),auth.uid())
    returning id into v_quiz_id;
  else
    select id into v_quiz_id from public.quizzes where id=p_quiz_id and module_id=p_module_id;
    if v_quiz_id is null then raise exception 'Cuestionario no encontrado'; end if;

    update public.quizzes
      set title=trim(p_title),
          description=coalesce(p_description,''),
          position=greatest(coalesce(p_position,1),1),
          is_published=coalesce(p_is_published,true)
    where id=v_quiz_id;

    delete from public.quiz_questions where quiz_id=v_quiz_id;
  end if;

  for q in select value from jsonb_array_elements(p_questions)
  loop
    q_index := q_index + 1;
    if trim(coalesce(q->>'prompt',''))='' then raise exception 'Hay una pregunta vacía'; end if;
    if jsonb_array_length(coalesce(q->'options','[]'::jsonb)) < 2 then raise exception 'Cada pregunta necesita al menos dos opciones'; end if;
    correct_index := coalesce((q->>'correct_index')::integer,0);

    insert into public.quiz_questions(quiz_id,prompt,position)
    values(v_quiz_id,trim(q->>'prompt'),q_index)
    returning id into v_question_id;

    opt_index := 0;
    for opt in select value #>> '{}' from jsonb_array_elements(q->'options')
    loop
      if trim(coalesce(opt,''))<>'' then
        insert into public.quiz_options(question_id,label,is_correct,position)
        values(v_question_id,trim(opt),opt_index=correct_index,opt_index+1);
      end if;
      opt_index := opt_index + 1;
    end loop;
  end loop;

  return v_quiz_id;
end;
$$;

revoke all on function public.save_quiz(bigint,bigint,text,text,integer,boolean,jsonb) from public;
grant execute on function public.save_quiz(bigint,bigint,text,text,integer,boolean,jsonb) to authenticated;

-- ----------------------------------------------------------
-- 5. CARGAR QUIZ SIN EXPONER RESPUESTAS CORRECTAS
-- ----------------------------------------------------------
create or replace function public.get_quiz_for_user(p_quiz_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_course_id bigint;
  v_published boolean;
  result jsonb;
begin
  if auth.uid() is null then raise exception 'No autenticado'; end if;

  select m.course_id,q.is_published into v_course_id,v_published
  from public.quizzes q
  join public.modules m on m.id=q.module_id
  where q.id=p_quiz_id;

  if v_course_id is null then raise exception 'Cuestionario no encontrado'; end if;
  if not public.is_admin() and not public.user_belongs_to_course(v_course_id) then raise exception 'Sin acceso al curso'; end if;
  if v_published=false and public.current_user_role()='student' then raise exception 'Cuestionario no publicado'; end if;

  select jsonb_build_object(
    'id',q.id,
    'title',q.title,
    'description',q.description,
    'questions',coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',qq.id,
          'prompt',qq.prompt,
          'options',coalesce((
            select jsonb_agg(jsonb_build_object('id',qo.id,'label',qo.label) order by qo.position)
            from public.quiz_options qo
            where qo.question_id=qq.id
          ),'[]'::jsonb)
        ) order by qq.position
      )
      from public.quiz_questions qq
      where qq.quiz_id=q.id
    ),'[]'::jsonb)
  )
  into result
  from public.quizzes q
  where q.id=p_quiz_id;

  return result;
end;
$$;

revoke all on function public.get_quiz_for_user(bigint) from public;
grant execute on function public.get_quiz_for_user(bigint) to authenticated;

-- ----------------------------------------------------------
-- 6. CORREGIR Y GUARDAR INTENTO
-- ----------------------------------------------------------
create or replace function public.submit_quiz(p_quiz_id bigint,p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_course_id bigint;
  v_total integer;
  v_score integer;
  v_attempt_id bigint;
begin
  if auth.uid() is null then raise exception 'No autenticado'; end if;

  select m.course_id into v_course_id
  from public.quizzes q join public.modules m on m.id=q.module_id
  where q.id=p_quiz_id and q.is_published=true;

  if v_course_id is null then raise exception 'Cuestionario no disponible'; end if;
  if not public.is_admin() and not public.user_belongs_to_course(v_course_id) then raise exception 'Sin acceso al curso'; end if;

  select count(*) into v_total from public.quiz_questions where quiz_id=p_quiz_id;

  select count(*) into v_score
  from public.quiz_questions qq
  join public.quiz_options qo
    on qo.question_id=qq.id
   and qo.is_correct=true
  where qq.quiz_id=p_quiz_id
    and (p_answers ->> qq.id::text) is not null
    and (p_answers ->> qq.id::text)::bigint = qo.id;

  insert into public.quiz_attempts(quiz_id,user_id,score,total,answers)
  values(p_quiz_id,auth.uid(),v_score,v_total,coalesce(p_answers,'{}'::jsonb))
  returning id into v_attempt_id;

  return jsonb_build_object(
    'attempt_id',v_attempt_id,
    'score',v_score,
    'total',v_total,
    'percentage',case when v_total>0 then round((v_score::numeric/v_total::numeric)*100) else 0 end
  );
end;
$$;

revoke all on function public.submit_quiz(bigint,jsonb) from public;
grant execute on function public.submit_quiz(bigint,jsonb) to authenticated;
