-- ==========================================================
-- CÓRDOBA CASTING · AULA VIRTUAL · V14 UNIFICADA
-- Incluye:
--   A) V11: edición de foro + cambio Alumno/Profesor desde el Aula
--   B) Desafíos globales con entregas y devolución
--   C) Notificaciones de nuevos desafíos
--
-- Esta migración está pensada para ejecutar sobre la versión V10,
-- SIN haber ejecutado V11, V12 ni V13.
-- ==========================================================

-- ==========================================================
-- A. FORO · PROFESORES Y ADMIN PUEDEN EDITAR
-- ==========================================================

drop policy if exists "Staff can update forum threads" on public.forum_threads;
create policy "Staff can update forum threads"
on public.forum_threads
for update
to authenticated
using (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and public.user_belongs_to_course(course_id)
  )
)
with check (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and public.user_belongs_to_course(course_id)
  )
);

drop policy if exists "Staff can update forum replies" on public.forum_replies;
create policy "Staff can update forum replies"
on public.forum_replies
for update
to authenticated
using (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and exists (
      select 1
      from public.forum_threads t
      where t.id = forum_replies.thread_id
        and public.user_belongs_to_course(t.course_id)
    )
  )
)
with check (
  public.is_admin()
  or (
    public.current_user_role() = 'teacher'
    and exists (
      select 1
      from public.forum_threads t
      where t.id = forum_replies.thread_id
        and public.user_belongs_to_course(t.course_id)
    )
  )
);

-- ==========================================================
-- B. ADMIN · CAMBIAR ALUMNO ↔ PROFESOR DESDE EL AULA
-- ==========================================================

create or replace function public.admin_set_user_role(
  target_user_id uuid,
  new_role text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_target_role text;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;

  if not public.is_admin() then
    raise exception 'Sólo un administrador puede cambiar roles';
  end if;

  if new_role not in ('student','teacher') then
    raise exception 'Rol no permitido';
  end if;

  select role
  into current_target_role
  from public.profiles
  where id = target_user_id;

  if current_target_role is null then
    raise exception 'Usuario no encontrado';
  end if;

  if current_target_role = 'admin' then
    raise exception 'Los administradores no se modifican desde esta opción';
  end if;

  update public.profiles
  set role = new_role
  where id = target_user_id;
end;
$$;

revoke all on function public.admin_set_user_role(uuid,text) from public;
grant execute on function public.admin_set_user_role(uuid,text) to authenticated;

-- ==========================================================
-- C. DESAFÍOS GLOBALES
-- ==========================================================

create table if not exists public.challenge_cards (
  id bigint generated by default as identity primary key,
  category text not null,
  duration_label text,
  focus text not null,
  prompt text not null,
  rules jsonb not null default '[]'::jsonb,
  dialogue_lines jsonb not null default '[]'::jsonb,
  position integer not null default 1,
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_attempts (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.challenge_cards(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  dialogue_line text not null,
  submission_url text not null,
  reflection text,
  status text not null default 'submitted'
    check (status in ('submitted','reviewed','completed')),
  feedback text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.challenge_cards enable row level security;
alter table public.challenge_attempts enable row level security;

drop policy if exists "Authenticated read published challenges" on public.challenge_cards;
create policy "Authenticated read published challenges"
on public.challenge_cards
for select
to authenticated
using (is_published or public.is_admin());

drop policy if exists "Admin manages challenges" on public.challenge_cards;
create policy "Admin manages challenges"
on public.challenge_cards
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users read own challenge attempts" on public.challenge_attempts;
create policy "Users read own challenge attempts"
on public.challenge_attempts
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users submit own challenges" on public.challenge_attempts;
create policy "Users submit own challenges"
on public.challenge_attempts
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.challenge_cards c
    where c.id = challenge_id
      and c.is_published
  )
);

drop policy if exists "Admin reviews challenge attempts" on public.challenge_attempts;
create policy "Admin reviews challenge attempts"
on public.challenge_attempts
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Banco inicial.
-- IMPORTANTE: todos quedan PAUSADOS para que el admin decida
-- cuál publicar como desafío semanal.
insert into public.challenge_cards
  (category,duration_label,focus,prompt,rules,dialogue_lines,position,is_published)
select *
from (
  values
  ('Cámara','5 min','Economía frente a cámara','Hacé dos tomas con la misma línea. En la primera permití toda la expresividad que aparezca. En la segunda reducí gestos y movimientos, pero mantené el mismo pensamiento y necesidad.','["Primer plano o plano medio corto.", "No cambies la intención entre tomas.", "Mirá ambas y detectá qué sigue llegando cuando hacés menos."]'::jsonb,'["Quedate un segundo.", "No era eso lo que te pregunté.", "¿Eso es todo?", "No me mires así.", "Pensé que ibas a venir."]'::jsonb,1,false),
  ('Escucha','10 min','Reacción antes que respuesta','Tu compañero te dice una frase. No prepares la respuesta. Permití que lo que escuchás produzca algo y recién entonces decí la línea sorteada.','["No fabriques una pausa.", "La reacción puede ser mínima.", "Repetilo cambiando lo que te dice tu compañero, no tu línea."]'::jsonb,'["No hace falta que me expliques.", "¿Hace cuánto lo sabés?", "Decime que no es verdad.", "Pensé que esto iba a ser distinto.", "¿Eso es todo?"]'::jsonb,2,false),
  ('Meisner','15 min','Concentración, escucha y conducta','A realiza una actividad que realmente requiere concentración. B entra necesitando algo urgente. En algún momento debe aparecer la línea sorteada, sin decidir de antemano cuándo.','["La actividad tiene que ser posible y difícil.", "Ambos necesitan algo concreto.", "No detengan la escena para meter la frase."]'::jsonb,'["Prometeme que no vas a decir nada.", "Necesito que confíes en mí.", "No lo hagas más difícil.", "¿Querés que me vaya?", "Yo me encargo."]'::jsonb,3,false),
  ('Imaginación','5 min','Especificidad e imaginación visible','Elegí un objeto cotidiano y construí una circunstancia en la que sea decisivo para vos. Durante los primeros 30 segundos no hablás. Después decís únicamente la línea sorteada.','["No expliques qué significa el objeto.", "No uses música.", "La relación con el objeto tiene que cambiar el modo en que aparece la frase."]'::jsonb,'["Dejá eso donde estaba.", "No tendrías que estar acá.", "Pensé que ibas a venir.", "No fue así.", "Te estaba esperando."]'::jsonb,4,false),
  ('Acción','10 min','Objetivo estable, tácticas variables','Tu objetivo no cambia. Probá conseguirlo usando tres acciones diferentes. La línea sorteada es siempre la misma; cambia lo que intentás hacerle al otro con ella.','["Usá verbos jugables.", "No elijas emociones.", "Cambiá de acción cuando la anterior deje de funcionar."]'::jsonb,'["Podés irte si querés.", "Está bien, te creo.", "No hace falta que me expliques.", "Yo me encargo.", "No me mires así."]'::jsonb,5,false),
  ('Subtexto','10 min','Separar palabras, acción e intención','Construí una situación en la que lo que necesitás contradiga la literalidad de la línea sorteada.','["No agregues explicación.", "Mantené la contradicción jugable, no intelectual.", "Hacé una segunda toma invirtiendo el subtexto."]'::jsonb,'["Podés irte si querés.", "Está bien, te creo.", "No quiero hablar de eso.", "No hace falta que me expliques.", "¿Querés que me vaya?"]'::jsonb,6,false),
  ('Personaje','10 min','Personaje a través de conducta','Creá un personaje desde necesidad y conducta. Filmá 20 segundos de espera antes de decir la línea sorteada.','["Definí qué necesita y qué evita.", "No llenes la espera con gestos.", "La línea debe aparecer como consecuencia de esa espera."]'::jsonb,'["Te estaba esperando.", "Pensé que ibas a venir.", "¿Hace cuánto lo sabés?", "No tendrías que estar acá.", "¿Eso es todo?"]'::jsonb,7,false),
  ('Casting','10 min','Decisión clara con poco tiempo','Tenés cinco minutos para preparar la línea sorteada como si fuera una prueba de casting: quién sos, qué acaba de pasar, qué querés, dónde está tu interlocutor y qué cambia.','["Encuadre simple y sonido claro.", "Eyeline consistente.", "Una sola toma final después de preparar."]'::jsonb,'["No era eso lo que te pregunté.", "Volvé a decirlo.", "¿Por qué viniste?", "No lo hagas más difícil.", "Necesito que confíes en mí."]'::jsonb,8,false)
) as seed(category,duration_label,focus,prompt,rules,dialogue_lines,position,is_published)
where not exists (
  select 1 from public.challenge_cards
);

-- ==========================================================
-- D. NOTIFICACIONES DE DESAFÍOS NUEVOS
-- ==========================================================

create table if not exists public.challenge_seen (
  user_id uuid not null references public.profiles(id) on delete cascade,
  challenge_id bigint not null references public.challenge_cards(id) on delete cascade,
  seen_at timestamptz not null default now(),
  primary key(user_id, challenge_id)
);

alter table public.challenge_seen enable row level security;

drop policy if exists "Users read own challenge seen" on public.challenge_seen;
create policy "Users read own challenge seen"
on public.challenge_seen
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users mark own challenge seen" on public.challenge_seen;
create policy "Users mark own challenge seen"
on public.challenge_seen
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users update own challenge seen" on public.challenge_seen;
create policy "Users update own challenge seen"
on public.challenge_seen
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- FIN V14
