-- ==========================================================
-- CÓRDOBA CASTING · AULA VIRTUAL · V4
-- PROFES + AVATARES + BIBLIOTECA DE EJERCICIOS + GUIONES
-- Ejecutar después de supabase_v3_pdf.sql
-- ==========================================================

-- 1. AVATAR
alter table public.profiles add column if not exists avatar_key text default 'meryl';

create or replace function public.set_my_avatar(new_avatar_key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if new_avatar_key not in ('meryl','susan','stella','stanislavski','viola','tilda') then
    raise exception 'Avatar no válido';
  end if;
  update public.profiles set avatar_key=new_avatar_key where id=auth.uid();
end;
$$;

revoke all on function public.set_my_avatar(text) from public;
grant execute on function public.set_my_avatar(text) to authenticated;

-- 2. DIRECTORIO DE PROFES
-- Devuelve únicamente nombre, rol, avatar y cursos. No expone email.
create or replace function public.get_teacher_directory()
returns table(
  user_id uuid,
  full_name text,
  role text,
  avatar_key text,
  course_id bigint,
  course_name text,
  course_code text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.full_name,
    p.role,
    p.avatar_key,
    c.id,
    c.name,
    c.code
  from public.profiles p
  left join public.course_members cm on cm.user_id=p.id
  left join public.courses c on c.id=cm.course_id and c.is_active=true
  where p.role in ('teacher','admin')
  order by p.full_name,c.name;
$$;

revoke all on function public.get_teacher_directory() from public;
grant execute on function public.get_teacher_directory() to authenticated;

-- 3. ESPACIOS DOCENTES
create table if not exists public.staff_spaces(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  created_at timestamptz not null default now()
);

insert into public.staff_spaces(slug,title,description)
values
  ('exercise-library','Biblioteca de ejercicios','Ejercicios, dinámicas y recursos compartidos para preparar clases.'),
  ('scripts','Guiones','Guiones y escenas compartidos entre el equipo docente.')
on conflict (slug) do update set title=excluded.title,description=excluded.description;

create table if not exists public.staff_modules(
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.staff_spaces(id) on delete cascade,
  title text not null,
  description text,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_lessons(
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.staff_modules(id) on delete cascade,
  title text not null,
  description text,
  content_type text not null default 'video'
    check(content_type in ('video','drive','link','text','pdf')),
  content_url text,
  text_content text,
  position integer not null default 1,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.staff_spaces enable row level security;
alter table public.staff_modules enable row level security;
alter table public.staff_lessons enable row level security;

-- Staff puede leer los dos espacios.
drop policy if exists "Staff can read staff spaces" on public.staff_spaces;
create policy "Staff can read staff spaces" on public.staff_spaces
for select to authenticated
using(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Staff can read staff modules" on public.staff_modules;
create policy "Staff can read staff modules" on public.staff_modules
for select to authenticated
using(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Staff can create staff modules" on public.staff_modules;
create policy "Staff can create staff modules" on public.staff_modules
for insert to authenticated
with check(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Staff can update staff modules" on public.staff_modules;
create policy "Staff can update staff modules" on public.staff_modules
for update to authenticated
using(public.current_user_role() in ('teacher','admin'))
with check(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Admin can delete staff modules" on public.staff_modules;
create policy "Admin can delete staff modules" on public.staff_modules
for delete to authenticated using(public.is_admin());

drop policy if exists "Staff can read staff lessons" on public.staff_lessons;
create policy "Staff can read staff lessons" on public.staff_lessons
for select to authenticated
using(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Staff can create staff lessons" on public.staff_lessons;
create policy "Staff can create staff lessons" on public.staff_lessons
for insert to authenticated
with check(
  public.current_user_role() in ('teacher','admin')
  and created_by=auth.uid()
);

drop policy if exists "Staff can update staff lessons" on public.staff_lessons;
create policy "Staff can update staff lessons" on public.staff_lessons
for update to authenticated
using(public.current_user_role() in ('teacher','admin'))
with check(public.current_user_role() in ('teacher','admin'));

drop policy if exists "Admin can delete staff lessons" on public.staff_lessons;
create policy "Admin can delete staff lessons" on public.staff_lessons
for delete to authenticated using(public.is_admin());

-- 4. STORAGE PRIVADO PARA PDF DE MATERIAL DOCENTE
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('staff-pdfs','staff-pdfs',false,52428800,array['application/pdf'])
on conflict(id) do update
set public=false,file_size_limit=52428800,allowed_mime_types=array['application/pdf'];

drop policy if exists "Staff can read staff pdfs" on storage.objects;
create policy "Staff can read staff pdfs" on storage.objects
for select to authenticated
using(bucket_id='staff-pdfs' and public.current_user_role() in ('teacher','admin'));

drop policy if exists "Staff can upload staff pdfs" on storage.objects;
create policy "Staff can upload staff pdfs" on storage.objects
for insert to authenticated
with check(bucket_id='staff-pdfs' and public.current_user_role() in ('teacher','admin'));

drop policy if exists "Admin can delete staff pdfs" on storage.objects;
create policy "Admin can delete staff pdfs" on storage.objects
for delete to authenticated
using(bucket_id='staff-pdfs' and public.is_admin());
